#!/usr/bin/env bash
set -xu

export CONDA_EXE=mamba
export NOW=$(date -Ins)

echo "# NOW: ${NOW}"  >> hourhouse.txt
pip freeze            >> hourhouse.txt

conda install code-server
code-server --install-extension ms-python.python

# bau
python -m hourhaus || echo >> ERROR.txt

export THEN=$(date -Ins)
echo "# THEN: ${THEN}" >> hourhouse.txt
pip freeze             >> hourhouse.txt
